### ISSUE TITLE
Set up Authentication using NextAuth

### ISSUE THREAD

**Issue by Saga-sanga** [chingu-voyages/v46-tier3-team-28#21]
**__Task Description__**
- [x] Setup NextAuth for the project.
- [x] Link NextAuth to database.
- [x] Add credentials login / sign up.
- [x] Add GitHub and Google SSO.

**__Technical Considerations__**
Required library:
- [NextAuth](https://next-auth.js.org/getting-started/example)
