### ISSUE TITLE
[Epic]: Create and Manage Collections

### ISSUE THREAD

**Issue by Saga-sanga** [chingu-voyages/v46-tier3-team-28#44]
\***\*Feature Description\*\***
Upon logging into the application, inside the `/dashboard` page the user should be able to view multiple collections and rearrange and edit them.

\***\*Major User Stories/tasks\*\***

- [ ] Create new collection #27 
- [ ] Edit existing collection #42
- [ ] (optional) rearrange the order of collections #43
