### ISSUE TITLE
[Epic]: Add and mange Items in collections

### ISSUE THREAD

**Issue by Saga-sanga** [chingu-voyages/v46-tier3-team-28#48]
\***\*Feature Description\*\***
Upon creating collections, users should be able to add items to the collections and edit or delete them.

\***\*Major User Stories/tasks\*\***

- [ ] Create a new item #45
- [ ] Edit existing item #46
- [ ] Delete an item #47
